
const PAGES = [
    { title: "Portada", id: 1, component: 'Slider1'},
    { title: "1. Presentación (Obligatoria)", id: 2, component: 'Slider2'},
    { title: "2. Mapa conceptual (Obligatoria)", id: 3, component: 'Slider3'},
    { title: "3. Nube de conceptos", id: 4, component: 'Slider4'},
    { title: "", id: 5, component: 'Slider5'},
    { title: "4. Texto con imagen", id: 6, component: 'Slider6'},
    { title: "5. Texto con imagen y títulos desplegables", id: 7, component: 'Slider7'},
    { title: "6. Texto con imagen y menú desplegable", id: 8, component: 'Slider8'},
    { title: "7. Texto con imagen grande", id: 9, component: 'Slider9'},
    { title: "8. Texto con carrousel de imágenes", id: 10, component: 'Slider10'},
    { title: "9. Cita", id: 11, component: 'Slider11'},
    { title: "10. Varias citas", id: 12, component: 'Slider12'},
    { title: "11. Pregunta sin respuesta", id: 13, component: 'Slider13'},
    { title: "12. Varias preguntas sin respuesta", id: 14, component: 'Slider14'},
    { title: "13. Pregunta con respuesta", id: 15, component: 'Slider15'},
    { title: "14. Pregunta con indicaciones", id: 16, component: 'Slider16'},
    { title: "15. Cuestionario de verificación", id: 17, component: 'Slider17'},
    { title: "16. Cuestionario de texto", id: 18, component: 'Slider18'},
    { title: "17. Tarjetas giratorias", id: 19, component: 'Slider19'},
    { title: "18. Texto con menú desplegable", id: 20, component: 'Slider20'},
    { title: "19. Texto con títulos desplegables", id: 21, component: 'Slider21'},
    { title: "20. Texto con títulos desplegables horizontal", id: 22, component: 'Slider22'},
    { title: "21. Texto con tabla dinámica", id: 23, component: 'Slider23'},
    { title: "22. Vídeo (Obligatorio)", id: 24, component: 'Slider24'},
    { title: "23. Línea de tiempo", id: 25, component: 'Slider25'},
    { title: "24. Relaciona los términos", id: 26, component: 'Slider26'},
    { title: "25. Rosco de definiciones", id: 27, component: 'Slider27'},
    { title: "26. Test", id: 28, component: 'Slider28'},
    { title: "", id: 29, component: 'Slider29'},
    { title: "27. Texto", id: 30, component: 'Slider30'},
    { title: "28. Evaluación", id: 31, component: 'Slider31'},
    { title: "29. Glosario (Obligatorio)", id: 32, component: 'Slider32'},
    { title: "30. Enlaces de interés (Obligatorio)", id: 33, component: 'Slider33'},
    { title: "31. Bibliografía (Obligatioria)", id: 34, component: 'Slider34'},
    { title: "32. Valoración", id: 35, component: 'Slider35'},
    { title: "Créditos", id: 36, component: 'Slider36'},
]


export default PAGES;