import dotenv from 'dotenv';
import configuration from '../public/configuration';
dotenv.config();
import Evaluation from '../src/components/Evaluation';

const baseEndpointURL = process.env.REACT_APP_MULESOFT_API_URL;
const scormFaculty = process.env.REACT_APP_SCORM_FACULTY;
const scormDegree = process.env.REACT_APP_SCORM_DEGREE;
const scormAuthors = process.env.REACT_APP_SCORM_AUTHORS;
const scormAuthorEmails = process.env.REACT_APP_SCORM_AUTHORS_EMAIL;
const scormPages = process.env.REACT_APP_SCORM_PAGES;
const scormName = process.env.REACT_APP_SCORM_NAME;

const baseEndpointURLValue = 'https://ucjc-scorm-exp-api-prod.de-c1.cloudhub.io/api/v1/';

const scormFacultyValues = [
    'Facultad de Comunicación y Humanidades',
    'Facultad de Educación',
    'Facultad de Salud',
    'Facultad de Tecnología y Ciencia',
]

const scormDegreeValues = [
    'Grado en Comunicación Audiovisual y Nuevos Medios',
    'Grado en Cine y Ficción Audiovisual',
    'Grado en Criminología y Seguridad',
    'Grado en Derecho',
    'Grado en Protocolo y Organización de Eventos',
    'Grado en Publicidad Creativa',
    'Grado en Maestro en Educación Infantil',
    'Grado en Maestro en Educación Primaria',
    'Grado en Pedagogía',
    'Grado en Ciencias de la Actividad Física y del Deporte',
    'Grado en Enfermería',
    'Grado en Fisioterapia',
    'Grado en Psicología',
    'Grado en Artes Digitales',
    'Grado en Empresa y Tecnología',
    'Grado en Emprendimiento y Gestión de Empresas',
    'Grado en Ingeniería Informática',
    'Grado en Gestión Urbana',
    'Grado en Transporte y Logística'
]

const scormAuthorValues = [
{"name":"Abel Romero Ugart","email":"aromerou@ucjc.edu"},
{"name":"Ada Cristina Freitas Cortina","email":"afreitas@ucjc.edu"},
{"name":"Adela Encarnación Cortijo Cantos","email":"acortijo@ucjc.edu"},
{"name":"Adolfo Calatrava García","email":"acalatrava@ucjc.edu"},
{"name":"Adriana Atencio Antoranz","email":"adriana.atencio@ucjc.edu"},
{"name":"Adrián Andrada Chacón","email":"aandrada@ucjc.edu"},
{"name":"Adrián Martín Pascual","email":"adrian.martinp@sek.es"},
{"name":"África Presol Herrero","email":"apresol@ucjc.edu"},
{"name":"Agni William Castro Pita","email":"awcastro@ucjc.edu"},
{"name":"Agustina Soledad Rimondi Melneciuc","email":"arimondi@ucjc.edu"},
{"name":"Agustín Sánchez Alhambra","email":"asanchez@ucjc.edu"},
{"name":"Aikaterini Evangelia Psegiannaki","email":"aepsegiannaki@ucjc.edu"},
{"name":"Ainhoa Arana Cuenca","email":"aarana@ucjc.edu"},
{"name":"Ainoa Blas Parra","email":"ablasp@ucjc.edu"},
{"name":"Aitana Elena Tamayo Hernando","email":"aetamayo@ucjc.edu"},
{"name":"Aitor Canibe Sánchez","email":"acanibe@ucjc.edu"},
{"name":"Aitor Ruiz de Lara Osacar","email":"aruizl@ucjc.edu"},
{"name":"Alain Sola Vicente","email":"asola@ucjc.edu"},
{"name":"Alan Burton Goodman","email":"abgoodman@ucjc.edu"},
{"name":"Alan Schroeder","email":"aschroeder@ucjc.edu"},
{"name":"Alan Schroeder","email":"p-aschroeder@ucjc.edu"},
{"name":"Alba Barros Guerrero","email":"abarros@ucjc.edu"},
{"name":"Alba Villasán Rueda","email":"avillasan@ucjc.edu"},
{"name":"Alberto Ballesteros Rodríguez","email":"alberto.ballesterosr@ucjc.edu"},
{"name":"Alberto Cique Moya","email":"acique@ucjc.edu"},
{"name":"Alberto Natal Delgado","email":"alberto.natal@ucjc.edu"},
{"name":"Alberto Sánchez Sierra","email":"asierra@ucjc.edu"},
{"name":"Alberto Sanmiguel Rodríguez","email":"asanmiguel@ucjc.edu"},
{"name":"Alberto Villalba García","email":"alberto.villalbag@ucjc.edu"},
{"name":"Alejandra Artero Muñoz","email":"alejandra.arterom@ucjc.edu"},
{"name":"Alejandro Del Pino Tortonda","email":"adelpino@ucjc.edu"},
{"name":"Alejandro Echeverría Rey","email":"aecheverria@ucjc.edu"},
{"name":"Alejandro López-Riobóo Moreno","email":"alopez-rioboo@ucjc.edu"},
{"name":"Alejandro Mendibil Blanco","email":"amendibil@ucjc.edu"},
{"name":"Alejandro Scatton Londero","email":"ascatton@ucjc.edu"},
{"name":"Alexis Louise Harvey","email":"aharvey@ucjc.edu"},
{"name":"Alfonso Prieto González","email":"alfonso.prietog@ucjc.edu"},
{"name":"Alfredo Antonio Rodríguez Gómez","email":"agomez@ucjc.edu"},
{"name":"Alfredo Crespo Alcázar","email":"acrespo@ucjc.edu"},
{"name":"Alfredo Dávalos López","email":"adavalos@ucjc.edu"},
{"name":"Alicia Alvarado Escudero","email":"aalvarado@ucjc.edu"},
{"name":"Alicia Villán Rodríguez","email":"avillan@ucjc.edu"},
{"name":"Alisha Singh","email":"alisha.singh@ucjc.edu"},
{"name":"Almudena Baeza Medina","email":"abaeza@ucjc.edu"},
{"name":"Álvaro García-Romero Pérez","email":"agromero@ucjc.edu"},
{"name":"Álvaro Miguel Ortega","email":"amiguel@ucjc.edu"},
{"name":"Álvaro Moraleda Ruano","email":"amoraleda@ucjc.edu"},
{"name":"Álvaro Otero Campos","email":"aotero@ucjc.edu"},
{"name":"Álvaro Peralta Conde","email":"aperalta@ucjc.edu"},
{"name":"Álvaro Sola Soria","email":"asolas@ucjc.edu"},
{"name":"Amador Álvarez Cózar","email":"aalvarez@ucjc.edu"},
{"name":"Amalia Herencia Grillo","email":"aherencia@ucjc.edu"},
{"name":"Amalia Juana Escalona Martínez","email":"aescalona@ucjc.edu"},
{"name":"Amanda Hernández Soto","email":"ahsoto@ucjc.edu"},
{"name":"Amy Baxter Mertzlufft","email":"abaxter@ucjc.edu"},
{"name":"Ana Alonso Martín","email":"amalonso@ucjc.edu"},
{"name":"Ana Amelia Serrano Girau","email":"aserrano@ucjc.edu"},
{"name":"Anabel Amores Ampuero","email":"aamores@ucjc.edu"},
{"name":"Ana Belén Carmona Rubio","email":"abcarmona@ucjc.edu"},
{"name":"Ana Belén Frías López-Tofiño","email":"afrias@sek.es"},
{"name":"Ana Belén Oliver González","email":"aboliver@ucjc.edu"},
{"name":"Ana Belén Sánchez Calzón","email":"absanchez@ucjc.edu"},
{"name":"Ana Calderón Granizo","email":"acalderon@ucjc.edu"},
{"name":"Ana Crespo Ibáñez","email":"acrespoi@ucjc.edu"},
{"name":"Ana Cristina Tomás López","email":"cristina.tomasl@ucjc.edu"},
{"name":"Ana García Díaz","email":"agarcia@ucjc.edu"},
{"name":"Ana Gisela Yépez Peñalver","email":"gyepez@ucjc.edu"},
{"name":"Ana Hoyas Gil","email":"ahoyas@ucjc.edu"},
{"name":"Ana Isabel Arcos Romero","email":"aisabel.arcos@ucjc.edu"},
{"name":"Ana Izarasua Batres Cuevas","email":"ibatres@ucjc.edu"},
{"name":"Analia Verónica Sarrautte","email":"averonica.sarrautte@ucjc.edu"},
{"name":"Ana Luz Luengo Tapia","email":"alluengo@ucjc.edu"},
{"name":"Ana María González Martín","email":"amgonzalez@ucjc.edu"},
{"name":"Ana María López Narbona","email":"amlopez@ucjc.edu"},
{"name":"Ana María Martín De la Sierra","email":"ammartin@ucjc.edu"},
{"name":"Ana María Martínez","email":"anamaria.martinez@ucjc.edu"},
{"name":"Ana María Molina Lebron","email":"amaria.molinal@ucjc.edu"},
{"name":"Ana María Moratalla Tolosa","email":"amaria.moratalla@ucjc.edu"},
{"name":"Ana María Peligero Molina","email":"ampeligero@ucjc.edu"},
{"name":"Ana María Rivas Machota","email":"amrivas@ucjc.edu"},
{"name":"Ana María Rodríguez Rodríguez","email":"amrodriguez@ucjc.edu"},
{"name":"Ana María Valtierra Lacalle","email":"avaltierra@ucjc.edu"},
{"name":"Ana Patricia de la Cruz Cardoso","email":"anapatricia.delacruz@sek.es"},
{"name":"Ana Pérez de Cámara González","email":"aperezdecamara@ucjc.edu"},
{"name":"Ana Rodríguez Morato","email":"arodriguez@ucjc.edu"},
{"name":"Ana Rosa Lagares Gaitán","email":"arlagares@ucjc.edu"},
{"name":"Ana Sánchez Rico","email":"asanchezr@ucjc.edu"},
{"name":"Ana Verde Trabada","email":"averde@ucjc.edu"},
{"name":"Andrea Enciso Acosta","email":"aenciso@ucjc.edu"},
{"name":"Andrea García-Santesmases Fernández","email":"agarcia-santesmases@ucjc.edu"},
{"name":"Andreas Schiffer","email":"aschiffer@ucjc.edu"},
{"name":"Andreina Sordo Castro","email":"asordo@ucjc.edu"},
{"name":"Andrés Arriaga Arrizabalaga","email":"andres.arriaga@ucjc.edu"},
{"name":"Andrés Dolón Sevilla","email":"andres.dolon@ucjc.edu"},
{"name":"Andrés Herrera Feligreras","email":"aherrera@ucjc.edu"},
{"name":"Andrés Sánchez Suricalday","email":"asanchezs@ucjc.edu"},
{"name":"Andreu Coll Sansalvador","email":"acoll@ucjc.edu"},
{"name":"Ángela Elena Otero Del Castillo","email":"aelena.otero@ucjc.edu"},
{"name":"Ángel Escudero De Paz","email":"aescudero@ucjc.edu"},
{"name":"Angélica Barrio Tordesillas","email":"abarrio@ucjc.edu"},
{"name":"Ángel Ignacio Rivas Pino","email":"airivas@ucjc.edu"},
{"name":"Ángel Luis González Olivares","email":"aluisgonzalez@ucjc.edu"},
{"name":"Ángel Mora Urda","email":"angel.mora@ucjc.edu"},
{"name":"Ángel Vicario Merino","email":"avicario@ucjc.edu"},
{"name":"Antoni Biarnés","email":"abiarnes@ucjc.edu"},
{"name":"Antonio Díaz Rodríguez","email":"adiaz@ucjc.edu"},
{"name":"Antonio Fonfría Mesa","email":"afonfria@ucjc.edu"},
{"name":"Antonio Gabriel Moreno Pimentel","email":"agmoreno@ucjc.edu"},
{"name":"Antonio Jesús Infante Sánchez","email":"ajinfante@ucjc.edu"},
{"name":"Antonio Muñoz del Viejo","email":"amunoz@ucjc.edu"},
{"name":"Antonio Pamos De la Hoz","email":"apamos@ucjc.edu"},
{"name":"Antonio Rivas González","email":"argonzalez@ucjc.edu"},
{"name":"Antonio Robles García","email":"argarcia@ucjc.edu"},
{"name":"Araceli Hernández López","email":"ahlopez@ucjc.edu"},
{"name":"Aránzazu García Heras","email":"agarciah@ucjc.edu"},
{"name":"Arturo Blanco Herrero","email":"aherrero@ucjc.edu"},
{"name":"Arturo Javier Monzó Ramón","email":"ajmonzo@ucjc.edu"},
{"name":"Arturo Merayo","email":"amerayo@ucjc.edu"},
{"name":"Asier Mañas Bote","email":"amanas@ucjc.edu"},
{"name":"Aurora González-Adalid Núñez","email":"agadalid@ucjc.edu"},
{"name":"Aurora Murga Aroca","email":"aurora.murga@ucjc.edu"},
{"name":"Azeez Abdul-Ghaffar Baig","email":"abaig@ucjc.edu"},
{"name":"Barbara Marchiori","email":"p-bmarchiori@ucjc.edu"},
{"name":"Beatriz Chamorro Gorines","email":"bchamorro@ucjc.edu"},
{"name":"Beatriz De Vicente De Castro","email":"bvicente@ucjc.edu"},
{"name":"Beatriz Gal Iglesias","email":"beatriz.gal@ucjc.edu"},
{"name":"Beatriz Lara López","email":"blara@ucjc.edu"},
{"name":"Beatriz Lobato Sánchez","email":"blobato@ucjc.edu"},
{"name":"Beatriz Luceño Ramos","email":"bluceno@ucjc.edu"},
{"name":"Beatriz Mesa García","email":"beatriz.mesag@ucjc.edu"},
{"name":"Beatriz Rodríguez Sánchez","email":"brodriguez@ucjc.edu"},
{"name":"Begoña Lavín Plaza","email":"blavin@ucjc.edu"},
{"name":"Belén López Pérez","email":"blopez@ucjc.edu"},
{"name":"Benito Herrero Miguel","email":"benito.herrero@ucjc.edu"},
{"name":"Blanca Alejandra Caballero González","email":"bcaballero@ucjc.edu"},
{"name":"Blanca María Erviti Arbaiza","email":"berviti@ucjc.edu"},
{"name":"Blanca María Gómez Rodríguez","email":"bgomez@ucjc.edu"},
{"name":"Borja Herraiz Castro","email":"borja.herraiz@sek.es"},
{"name":"Borja Suárez Villadat","email":"bsuarez@ucjc.edu"},
{"name":"Bruno García Tardón","email":"btardon@ucjc.edu"},
{"name":"Camila Polensvaig Kominsky","email":"cpolensvaig@ucjc.edu"},
{"name":"Camilo Esteban Goelkel Medina","email":"cgoelkel@ucjc.edu"},
{"name":"Camino Ruiz Rodríguez","email":"crrodriguez@ucjc.edu"},
{"name":"Carlos Andrés Pérez Munera","email":"cpmunera@ucjc.edu"},
{"name":"Carlos Arroyo Abad","email":"carroyo@ucjc.edu"},
{"name":"Carlos Augusto Castillo Plaza","email":"cacastillo@ucjc.edu"},
{"name":"Carlos De la Hoz García","email":"cdelahoz@ucjc.edu"},
{"name":"Carlos Echeverría Jesús","email":"cecheverria@ucjc.edu"},
{"name":"Carlos Eduardo Polo Portes","email":"cpolo@ucjc.edu"},
{"name":"Carlos García Roda","email":"cgarciar@ucjc.edu"},
{"name":"Carlos Gutiérrez","email":"p-cgutierrez@ucjc.edu"},
{"name":"Carlos José De la Cruz Martín-Romo","email":"cdelacruz@ucjc.edu"},
{"name":"Carlos Lasarte González","email":"clasarte@ucjc.edu"},
{"name":"Carlos Magro Mazo","email":"carlos.magro@sek.es"},
{"name":"Carlos Pérez-Íñigo Mora","email":"cperezinigo@ucjc.edu"},
{"name":"Carlos Ruiz Moreno","email":"cruizm@ucjc.edu"},
{"name":"Carlos Sancho Álvarez","email":"csancho@ucjc.edu"},
{"name":"Carlos Santiso","email":"p-csantiso@ucjc.edu"},
{"name":"Carmelo Angulo Barturen","email":"cangulo@ucjc.edu"},
{"name":"Carmen Jordá Sanz","email":"cjorda@ucjc.edu"},
{"name":"Carmen Karbasi Santos","email":"carmen.karbasi@ucjc.edu"},
{"name":"Carmen Rita Castellano Hernández","email":"crcastellano@ucjc.edu"},
{"name":"Carmen Sánchez Ovcharov","email":"csovcharov@sek.es"},
{"name":"Carmen Teresa Casares Guillén","email":"ctcasares@ucjc.edu"},
{"name":"Carmen Torquemada Borge","email":"carmen.torquemada@ucjc.edu"},
{"name":"Carolina Castañeda García","email":"ccastaneda@ucjc.edu"},
{"name":"Carolina Fernández García","email":"cfernandez@ucjc.edu"},
{"name":"Cayetana Ruiz Zaldibar","email":"crzaldibar@ucjc.edu"},
{"name":"Cecilia Inés Theirs Rodríguez","email":"citheirs@ucjc.edu"},
{"name":"Cecilio Pérez Agudo","email":"ceperez@sek.es"},
{"name":"Celia Navarro Gil","email":"cnavarro@ucjc.edu"},
{"name":"Celia Roldán Alaminos","email":"celia.roldan@ucjc.edu"},
{"name":"César Gallo Salazar","email":"cgallo@ucjc.edu"},
{"name":"César López Pérez","email":"clopez@ucjc.edu"},
{"name":"César Pérez de Tudela","email":"cperez@ucjc.edu"},
{"name":"César Zárate Gómez","email":"czarate@ucjc.edu"},
{"name":"Charlie Jorge Fernández","email":"cjfernandez@ucjc.edu"},
{"name":"Christien Hernandez","email":"cbrannigan.hernandez@ucjc.edu"},
{"name":"Clara Rodríguez Salgado","email":"crsalgado@ucjc.edu"},
{"name":"Claudia Beatriz Alvarenga Capurro","email":"cbeatriz.alvarenga@ucjc.edu"},
{"name":"Claudia Píriz Cayado","email":"cpiriz@ucjc.edu"},
{"name":"Claudio Soriente","email":"csoriente@ucjc.edu"},
{"name":"Concepción Anguita Olmedo","email":"canguita@ucjc.edu"},
{"name":"Cristian Alberto Solís Mencía","email":"casolis@ucjc.edu"},
{"name":"Cristian Didier Hernández García","email":"cristiandidier.hernandez@ucjc.edu"},
{"name":"Cristina Bódalo Tejedor","email":"cbodalo@ucjc.edu"},
{"name":"Cristina Colastra Santos","email":"ccolastra@ucjc.edu"},
{"name":"Cristina De Porcellinis Pascau","email":"cristina.porcellinis@ucjc.edu"},
{"name":"Cristina González Rodríguez","email":"cgrodriguez@ucjc.edu"},
{"name":"Cristina María Lozano Hernández","email":"cmlozano@ucjc.edu"},
{"name":"Cristina María Torres Muñoz","email":"cmtorres@ucjc.edu"},
{"name":"Cristina Martínez Roldán","email":"cmroldan@ucjc.edu"},
{"name":"Cristina Ojedo Martín","email":"cojedo@ucjc.edu"},
{"name":"Cristina Roldán Fidalgo","email":"cristina.roldanf@ucjc.edu"},
{"name":"Daniela Derosas Contreras","email":"dderosas@ucjc.edu"},
{"name":"Daniel Alonso Martínez","email":"dalonsom@ucjc.edu"},
{"name":"Daniel Burrueco del Río","email":"daniel.burrueco@ucjc.edu"},
{"name":"Daniel Del Valle-Inclán Rodríguez de Miñón","email":"dvalleinclan@ucjc.edu"},
{"name":"Daniel Eduardo López Acuña","email":"delopez@ucjc.edu"},
{"name":"Daniel Esguevillas Cuesta","email":"desguevillas@ucjc.edu"},
{"name":"Daniel Madruga Maura","email":"dmadruga@ucjc.edu"},
{"name":"Daniel Martínez Rodríguez","email":"dmrodriguez@ucjc.edu"},
{"name":"Daniel Mielgo Bregazzi","email":"dmielgo@ucjc.edu"},
{"name":"Daniel Nery Esquibel de León","email":"desquibel@ucjc.edu"},
{"name":"Daniel Rodríguez González","email":"drodriguez@ucjc.edu"},
{"name":"Daniel Rodríguez Rodríguez","email":"drodriguezr@ucjc.edu"},
{"name":"Daniel Turienzo Fraile","email":"dturienzo@ucjc.edu"},
{"name":"Danilo Magistrali","email":"dmagistrali@ucjc.edu"},
{"name":"Darío Pérez Bodeguero","email":"dperez@ucjc.edu"},
{"name":"David Ángel Pajín Rey","email":"dapajin@ucjc.edu"},
{"name":"David Bordejé Prieto","email":"david.bordeje@ucjc.edu"},
{"name":"David Faustino Redoli Morchón","email":"dredoli@ucjc.edu"},
{"name":"David Hernández Gutiérrez","email":"dhernandezg@ucjc.edu"},
{"name":"David Hernández Martínez","email":"dhernandezm@ucjc.edu"},
{"name":"David Lanza Escobedo","email":"dlanza@ucjc.edu"},
{"name":"David Martínez Ruiz","email":"david.mruiz@ucjc.edu"},
{"name":"David Martín Moncunill","email":"david.martinm@ucjc.edu"},
{"name":"David Matesanz Ureña","email":"dmatesanz@ucjc.edu"},
{"name":"David Moreno Casas","email":"dmoreno@ucjc.edu"},
{"name":"David Muñoz González","email":"dmunoz@ucjc.edu"},
{"name":"David Pérez Manchón","email":"dpmanchon@ucjc.edu"},
{"name":"David Revesado Carballares","email":"drevesado@ucjc.edu"},
{"name":"Diana Belén Ruiz Vicente","email":"diruiz@ucjc.edu"},
{"name":"Diana Cembreros Castaño","email":"dcembreros@ucjc.edu"},
{"name":"Diana Gallego De Marcos","email":"dgallego@ucjc.edu"},
{"name":"Diana García-Miguel López","email":"dgarcia-miguel@ucjc.edu"},
{"name":"Diana Lara Requena","email":"dlara@ucjc.edu"},
{"name":"Diego Antonio Galán Casado","email":"dagalan@ucjc.edu"},
{"name":"Diego Elcoroiribe Gabilondo","email":"delcoroiribe@ucjc.edu"},
{"name":"Diego Federico De la Vega Merino","email":"ddelavega@ucjc.edu"},
{"name":"Diego Gutiérrez Del Pozo","email":"dgutierrez@ucjc.edu"},
{"name":"Diego José Moreno Gascón","email":"dmgascon@ucjc.edu"},
{"name":"Diego Rubén Rodríguez Regadera","email":"druben.rodriguez@ucjc.edu"},
{"name":"Diego Sánchez De la Cruz","email":"dsdelacruz@ucjc.edu"},
{"name":"Dionisio Escuredo Hogan","email":"descuredo@ucjc.edu"},
{"name":"Dirk Zabala","email":"p-dzabala@ucjc.edu"},
{"name":"Domingo Pérez Castaño","email":"dperezc@ucjc.edu"},
{"name":"Edgar Cabanas Díaz","email":"ecabanas@ucjc.edu"},
{"name":"Eduardo Cimadevilla Fernández-Pola","email":"ecimadevilla@ucjc.edu"},
{"name":"Eduardo García Garzón","email":"egarcia@ucjc.edu"},
{"name":"Eduardo González Vega","email":"egvega@ucjc.edu"},
{"name":"Eduardo José Corral Pugnaire","email":"ejcorral@ucjc.edu"},
{"name":"Edurne Úbeda D`Ocasar","email":"eubeda@ucjc.edu"},
{"name":"Elena Carrión Candel","email":"ecarrion@ucjc.edu"},
{"name":"Elena De Andrés Jiménez","email":"edeandres@ucjc.edu"},
{"name":"Elena de la Paz Berzal Alesanco","email":"elena.berzal@ucjc.edu"},
{"name":"Elena Jurado Pérez","email":"ejurado@ucjc.edu"},
{"name":"Elena Magdalena Duque Viña","email":"emagdalena.duque@ucjc.edu"},
{"name":"Elena Manrique Pascual","email":"emanrique@ucjc.edu"},
{"name":"Elena María Ruiz Sancho","email":"eruiz@ucjc.edu"},
{"name":"Elena Muñoz Abad","email":"emunoz@ucjc.edu"},
{"name":"Elena Sonsoles Rodríguez López","email":"esrodriguez@ucjc.edu"},
{"name":"Elena Teresa López Cobeñas","email":"etlopez@ucjc.edu"},
{"name":"Elisabet Elena Pérez Monsalve","email":"eelena.perez@ucjc.edu"},
{"name":"Elisabetta Bertola López","email":"ebertola@ucjc.edu"},
{"name":"Elisa Rodríguez Ortega","email":"erodriguezo@ucjc.edu"},
{"name":"Elizabeth Igartua Royston","email":"eigartua@ucjc.edu"},
{"name":"Elizabeth López Gómez","email":"egomez@ucjc.edu"},
{"name":"Elizabeth Ransanz Reyes","email":"eransanz@ucjc.edu"},
{"name":"Ellen Rose Bowen","email":"ebowen@ucjc.edu"},
{"name":"Eloísa López Martín","email":"eloisa.lopez@sek.es"},
{"name":"Elsa Del Campo Ramírez","email":"edelcampo@ucjc.edu"},
{"name":"Elvira del Carmen Cabrera Rodríguez","email":"eccabrera@ucjc.edu"},
{"name":"Emeterio Díez Puertas","email":"ediez@ucjc.edu"},
{"name":"Emilio Cañadas Rodríguez","email":"ecanadas@ucjc.edu"},
{"name":"Encarnación López Mateo","email":"elmateo@ucjc.edu"},
{"name":"Enrique Cebrián Sánchez","email":"ecebrian@ucjc.edu"},
{"name":"Enrique de la Hoz de la Hoz","email":"enrique.hoz@ucjc.edu"},
{"name":"Enrique Frías Martínez","email":"enrique.frias@ucjc.edu"},
{"name":"Enrique Huertas García","email":"ehuertas@ucjc.edu"},
{"name":"Enrique Tribaldos Macía","email":"etribaldos@ucjc.edu"},
{"name":"Ernesto Luis Filardi Carrero","email":"elfilardi@ucjc.edu"},
{"name":"Esmeralda Guillén Tortajada","email":"eguillen@ucjc.edu"},
{"name":"Ester Jiménez Ormeño","email":"ejimenez@ucjc.edu"},
{"name":"Esther Domínguez Jové","email":"edominguez@ucjc.edu"},
{"name":"Esther García Muñiz","email":"esther.garciam@ucjc.edu"},
{"name":"Eugenia Criado Clemente","email":"ecriado@ucjc.edu"},
{"name":"Eugenio Pérez Francisco","email":"eperezf@ucjc.edu"},
{"name":"Eusebio López Reyes","email":"elreyes@ucjc.edu"},
{"name":"Eva Cano Fernández","email":"ecano@ucjc.edu"},
{"name":"Eva Elena Llergo Ojalvo","email":"ellergo@ucjc.edu"},
{"name":"Eva María Martínez Serrano","email":"emmartinez@ucjc.edu"},
{"name":"Eva María Teba Fernández","email":"eteba@ucjc.edu"},
{"name":"Evangelina García Montero","email":"egarmo@ucjc.edu"},
{"name":"Eva Patricia Fernández Manzano","email":"efernandez@ucjc.edu"},
{"name":"Eva Toledo Celada","email":"etoledo@ucjc.edu"},
{"name":"Farid Abdel Kader Mokhtar Ahmed Noriega","email":"fmokhtar@ucjc.edu"},
{"name":"Felicísimo Valbuena Fuente","email":"fvalbuena@ucjc.edu"},
{"name":"Felipe Maraña Marcos","email":"fmarana@ucjc.edu"},
{"name":"Félix Ladstatter","email":"felix.ladstatter@ucjc.edu"},
{"name":"Félix López Capel","email":"flcapel@ucjc.edu"},
{"name":"Félix López Sánchez","email":"flsanchez@ucjc.edu"},
{"name":"Félix Rafael Urosa Barreto","email":"furosa@ucjc.edu"},
{"name":"Fernando Domínguez Hernández","email":"fdominguez@ucjc.edu"},
{"name":"Fernando Ernesto Rubio Ahumada","email":"fernesto.rubio@ucjc.edu"},
{"name":"Fernando Evaristo Díaz Manzano","email":"fediaz@ucjc.edu"},
{"name":"Fernando Gordillo León","email":"fgordillo@ucjc.edu"},
{"name":"Fernando José Llorente Lobato","email":"fllorente@ucjc.edu"},
{"name":"Fernando José Seijo Martínez","email":"fjseijo@ucjc.edu"},
{"name":"Fernando María Amigo Quintana","email":"fmamigo@ucjc.edu"},
{"name":"Fernando Marqués Zornoza","email":"fmarques@ucjc.edu"},
{"name":"Fernando Martín Nieto","email":"fmnieto@ucjc.edu"},
{"name":"Fernando Moroy Hueto","email":"fmoroy@ucjc.edu"},
{"name":"Fernando Nieto Lobato","email":"fnieto@ucjc.edu"},
{"name":"Fernando Reyes Gil","email":"freyes@ucjc.edu"},
{"name":"Fernando Tellado García","email":"ftellado@ucjc.edu"},
{"name":"Fernando Tobías Moreno","email":"ftobias@ucjc.edu"},
{"name":"Fernando Vizcaíno De Sas","email":"fernando.vizcaino@ucjc.edu"},
{"name":"Florencia Ferrer","email":"p-fferrer@ucjc.edu"},
{"name":"Francisco Areces Corcuera","email":"fareces@ucjc.edu"},
{"name":"Francisco Cabello Santamaría","email":"fcabello@ucjc.edu"},
{"name":"Francisco Cano Broncano","email":"francisco.canob@ucjc.edu"},
{"name":"Francisco David Pascual Nicolás","email":"dpascual@ucjc.edu"},
{"name":"Francisco Javier Aragón Cánovas","email":"fjaragon@ucjc.edu"},
{"name":"Francisco Javier Esteban Guinea","email":"fjesteban@ucjc.edu"},
{"name":"Francisco Javier González Espadas","email":"fjgonzalez@ucjc.edu"},
{"name":"Francisco Javier López-Silvarrey Varela","email":"fjlopez-silvarrey@ucjc.edu"},
{"name":"Francisco Javier Montemayor Ruiz","email":"fmontemayor@ucjc.edu"},
{"name":"Francisco Javier Pericacho Gómez","email":"fpericacho@ucjc.edu"},
{"name":"Francisco Javier Peytibi Carbonel","email":"xpeytibi@ucjc.edu"},
{"name":"Francisco Javier San Martín María","email":"fjsanmartin@ucjc.edu"},
{"name":"Francisco José Amaro Gahete","email":"famaro@ucjc.edu"},
{"name":"Francisco José Herrada Martín","email":"fjherrada@ucjc.edu"},
{"name":"Francisco José Paredes Pérez","email":"fjose.paredes@ucjc.edu"},
{"name":"Francisco José Santamaría Ramos","email":"fsantamaria@ucjc.edu"},
{"name":"Francisco López Muñoz","email":"flopez@ucjc.edu"},
{"name":"Francisco Pérez Fernández","email":"fperez@ucjc.edu"},
{"name":"Francisco Soriano Nicolás","email":"fsoriano@ucjc.edu"},
{"name":"Gabriela Castillo Parra","email":"gcastillo@ucjc.edu"},
{"name":"Gabriel Jiménez Gómez","email":"gjgomez@ucjc.edu"},
{"name":"Gabriel Rosenthal Pereira","email":"grosenthal@ucjc.edu"},
{"name":"Gema Delia Arroyo Resino","email":"darroyo@ucjc.edu"},
{"name":"Gema González Carreño","email":"gcarreno@ucjc.edu"},
{"name":"Gema Hebrero Domínguez","email":"ghebrero@ucjc.edu"},
{"name":"Gerardo Arriaza Fernández","email":"garriaza@ucjc.edu"},
{"name":"Gisela Cebrián Bernat","email":"gcebrian@ucjc.edu"},
{"name":"Gisela Rubach","email":"p-grubach@ucjc.edu"},
{"name":"Gloria León Coronado","email":"gleon@ucjc.edu"},
{"name":"Gonzalo Duñaiturria Laguarda","email":"gdunaiturria@ucjc.edu"},
{"name":"Gonzalo Jaime Salas Claver","email":"gsalas@ucjc.edu"},
{"name":"Gracia Abad Quintanal","email":"gabad@ucjc.edu"},
{"name":"Gracia María Gallego Sendarrubias","email":"gmgallego@ucjc.edu"},
{"name":"Gregorio Jesús Alcalá Albert","email":"galcala@ucjc.edu"},
{"name":"Gregorio Martínez Villén","email":"gmartinez@ucjc.edu"},
{"name":"Guadalupe González Naranjo","email":"ggnaranjo@ucjc.edu"},
{"name":"Guido Bartolomé Corradi","email":"gcorradi@ucjc.edu"},
{"name":"Guillermo Díaz de Mera Rodríguez","email":"gdiaz@ucjc.edu"},
{"name":"Guillermo Enrique Boscán Carrasquero","email":"gboscan@ucjc.edu"},
{"name":"Guillermo José De la Torre Fernández de Vega","email":"guille.torre@ucjc.edu"},
{"name":"Guiseppe Emanuele Adamo","email":"giuseppeemanuele.adamo@ucjc.edu"},
{"name":"Gustavo Adolfo Sánchez Canales","email":"gscanales@ucjc.edu"},
{"name":"Gustavo Eduardo Toledo Lara","email":"gtoledo@ucjc.edu"},
{"name":"Gustavo Lescure Ceñal","email":"glescure@ucjc.edu"},
{"name":"Gustavo Tarre","email":"p-gtarre@ucjc.edu"},
{"name":"Héctor Galindo Domínguez","email":"hgalindo@ucjc.edu"},
{"name":"Henry Noah Hoffman","email":"hhoffman@ucjc.edu"},
{"name":"Heriberto Janosch González","email":"hjanosch@ucjc.edu"},
{"name":"Ignacio Ceballos Viro","email":"iceballos@ucjc.edu"},
{"name":"Ignacio De la Rosa Castro","email":"idelarosa@ucjc.edu"},
{"name":"Ignacio María De Luis Otero","email":"imdeluis@ucjc.edu"},
{"name":"Ignacio María Gordillo Álvarez-Valdés","email":"igordillo@ucjc.edu"},
{"name":"Ignacio Vicente De Ramón Burgos","email":"ideramon@ucjc.edu"},
{"name":"Imelda Rodríguez Escanciano","email":"irodriguez@ucjc.edu"},
{"name":"Iñaki Sainz de Murieta Fuentes","email":"inaki.sainz@ucjc.edu"},
{"name":"Inés Magán Uceda","email":"imagan@ucjc.edu"},
{"name":"Inés Sancho García","email":"isancho@ucjc.edu"},
{"name":"Iñigo Monzón Tobalina","email":"inigo.monzon@ucjc.edu"},
{"name":"Irene Guerrero Fernández","email":"iguerrero@ucjc.edu"},
{"name":"Irene Parra Lara","email":"iparra@ucjc.edu"},
{"name":"Irene Ruiz Miranda","email":"irene.ruizm@ucjc.edu"},
{"name":"Irma Lorenzo Capellá","email":"ilorenzo@ucjc.edu"},
{"name":"Isabel Morales Jareño","email":"imorales@ucjc.edu"},
{"name":"Isabel Soriano Villarroel","email":"isoriano@ucjc.edu"},
{"name":"Isidro Lapuente Álvarez","email":"ilapuente@ucjc.edu"},
{"name":"Ismael Martínez Guardado","email":"imartinez@ucjc.edu"},
{"name":"Israel González Pérez","email":"igonzalezp@ucjc.edu"},
{"name":"Israel Mañas Mañas","email":"imanas@ucjc.edu"},
{"name":"Israel Navarro García","email":"inavarrog@ucjc.edu"},
{"name":"Itziar Hernández Pereg","email":"ihernandez@ucjc.edu"},
{"name":"Itziar Sagasti García del Pozo","email":"isagasti@ucjc.edu"},
{"name":"Iulia Diana Furcila Mihalache","email":"dfurcila@ucjc.edu"},
{"name":"Iván Muñoz Puente","email":"ivan.munoz@ucjc.edu"},
{"name":"Jacobo Orellana Suárez","email":"jorellana@ucjc.edu"},
{"name":"Jaime Barrio Cortes","email":"jbarrio@ucjc.edu"},
{"name":"Jaime Chapa Huidobro","email":"jaime.chapa@sek.es"},
{"name":"Jaime Gómez Blaya","email":"jgomezb@ucjc.edu"},
{"name":"Jaime González García","email":"jgonzalezg@ucjc.edu"},
{"name":"Jaime Latorre Seoane","email":"jlatorre@ucjc.edu"},
{"name":"Jana Blanco Fernández","email":"jblancof@ucjc.edu"},
{"name":"Jana María Gallardo Pérez","email":"jgperez@ucjc.edu"},
{"name":"Jara González Lamas","email":"jglamas@ucjc.edu"},
{"name":"Javier Bermejo Fernández-Nieto","email":"jbermejo@ucjc.edu"},
{"name":"Javier Bernabé Fraguas","email":"jbernabe@ucjc.edu"},
{"name":"Javier Eladio Guzmán Villanueva","email":"jguzman@sek.es"},
{"name":"Javier Fadón Junyet","email":"jfadon@ucjc.edu"},
{"name":"Javier García Pacios","email":"jgpacios@ucjc.edu"},
{"name":"Javier Hernández Estrada","email":"jhernandez@ucjc.edu"},
{"name":"Javier Ijalba Pérez","email":"jijalba@ucjc.edu"},
{"name":"Javier Manuel Martínez de Aguirre Miral","email":"jmmartinez@ucjc.edu"},
{"name":"Javier Pinilla Arbex","email":"jpinilla@ucjc.edu"},
{"name":"Javier Prieto Vargas","email":"jprieto@ucjc.edu"},
{"name":"Javier Sempere Rodrigo","email":"jsempere@ucjc.edu"},
{"name":"Javier Simón Grima","email":"jsimon@ucjc.edu"},
{"name":"Javier Yuste Rodríguez-Escalona","email":"jyuste@ucjc.edu"},
{"name":"Jenny Alexandra Zuluaga Arévalo","email":"jazuluaga@ucjc.edu"},
{"name":"Jessica Méndez Fernández","email":"jessica.mendezf@ucjc.edu"},
{"name":"Jessica Moreno Pizarro","email":"jmoreno@ucjc.edu"},
{"name":"Jesús Abel Marrodán Gironés","email":"jesusabel.marrodan@ucjc.edu"},
{"name":"Jesús Ángel Megías López","email":"jamejias@ucjc.edu"},
{"name":"Jesús De Felipe Oroquieta","email":"jfelipe@ucjc.edu"},
{"name":"Jesús Guodemar Pérez","email":"jguodemar@ucjc.edu"},
{"name":"Jesús María Alquézar Sabadie","email":"p-jmalquezar@ucjc.edu"},
{"name":"Jesús María Amores Ampuero","email":"jmamores@ucjc.edu"},
{"name":"Jesús Martín Botella","email":"jmartin@ucjc.edu"},
{"name":"Jesús Miguel García García","email":"jmgarcia@ucjc.edu"},
{"name":"Jesús Torres Molina","email":"jtmolina@ucjc.edu"},
{"name":"Joanne Mampaso Desbrow","email":"jmampaso@ucjc.edu"},
{"name":"Jonatan Ríos Ayala","email":"jonatan.rios@ucjc.edu"},
{"name":"Jonathan Zaji Bar-Magen Numhauser","email":"jbarmagen@ucjc.edu"},
{"name":"Jone Escribano Fernández","email":"jone.escribano@ucjc.edu"},
{"name":"Jorge Antonio Vázquez Parra","email":"javazquez@ucjc.edu"},
{"name":"Jorge Bañeras Gómez-Tejedor","email":"jbaneras@ucjc.edu"},
{"name":"Jorge Barraca Mairal","email":"jbarraca@ucjc.edu"},
{"name":"Jorge Costa Vila","email":"jcosta@ucjc.edu"},
{"name":"Jorge Gallardo Camacho","email":"jgallardo@ucjc.edu"},
{"name":"Jorge Jiménez Serrano","email":"jjimenez@ucjc.edu"},
{"name":"Jorge Manuel Prieto Ballester","email":"jmprieto@ucjc.edu"},
{"name":"Jorge Santiago Barnés","email":"jfsantiago@ucjc.edu"},
{"name":"José Alberto Sotelo Martín","email":"jasotelo@ucjc.edu"},
{"name":"José Ángel Martínez Huertas","email":"jamartinez@ucjc.edu"},
{"name":"José Ángel Rollón Bragado","email":"jarollon@ucjc.edu"},
{"name":"José Antonio Carnevali Ramírez","email":"jacarnevali@ucjc.edu"},
{"name":"José Antonio Contreras Rosado","email":"jcontreras@ucjc.edu"},
{"name":"José Antonio Luengo Latorre","email":"jaluengo@ucjc.edu"},
{"name":"José Antonio Rodríguez Pascual","email":"jarodriguez@ucjc.edu"},
{"name":"José Antonio Vázquez Valencia","email":"jantonio.vazquezv@ucjc.edu"},
{"name":"Joseba Alonso Vélez","email":"jalonso@ucjc.edu"},
{"name":"José Carlos Aránguez Aránguez","email":"jcarlos.aranguez@ucjc.edu"},
{"name":"José Carlos Sanjuán Monforte","email":"jcsanjuan@ucjc.edu"},
{"name":"José Carlos Serrano Casasola","email":"jcserrano@ucjc.edu"},
{"name":"José Carpio","email":"p-jcarpio@ucjc.edu"},
{"name":"Jose Carpio Pinedo","email":"jcarpio@ucjc.edu"},
{"name":"José David Morales Betancourt","email":"jdmorales@ucjc.edu"},
{"name":"José De Arana Giralt","email":"jdearana@ucjc.edu"},
{"name":"José de Benito Gil","email":"jose.benito@ucjc.edu"},
{"name":"Josefa María Suárez Rodríguez","email":"jmsuarez@ucjc.edu"},
{"name":"José Fernando García Ródenas","email":"p-jgarcia@ucjc.edu"},
{"name":"Josefina García García-Cervigón","email":"jcervigon@ucjc.edu"},
{"name":"José Francisco Zamorano Abramson","email":"jfzamorano@ucjc.edu"},
{"name":"José Ignacio Saiz Herrera","email":"jisaiz@ucjc.edu"},
{"name":"José Ignacio Sanz Cámara","email":"jignacio.sanz@ucjc.edu"},
{"name":"José Javier Rainer Granados","email":"jjrainer@ucjc.edu"},
{"name":"José Javier Sanz Gil","email":"jjsanz@sek.es"},
{"name":"José Jesús Trujillo Vargas","email":"jjtrujillo@ucjc.edu"},
{"name":"José Luis Castán Esteban","email":"joseluis.castan@ucjc.edu"},
{"name":"José Luis Díez Martín","email":"jdiezm@ucjc.edu"},
{"name":"José Luis Llorente Perales","email":"jllorente@ucjc.edu"},
{"name":"José Luis Maté Muñoz","email":"jlmate@ucjc.edu"},
{"name":"José Luis Miguel Pedrero","email":"jlmiguel@ucjc.edu"},
{"name":"José Luis Toral Marinas","email":"jtoral@ucjc.edu"},
{"name":"José Luis Villa Martínez","email":"jlvilla@ucjc.edu"},
{"name":"José Manuel Blanco Gómez","email":"jmblanco@ucjc.edu"},
{"name":"José Manuel Castro Vázquez","email":"jmcastro@ucjc.edu"},
{"name":"José Manuel Quesada Campaña","email":"jmanuel.quesada@ucjc.edu"},
{"name":"José Manuel San Millán","email":"p-jmsanmillan@ucjc.edu"},
{"name":"José Manuel Toledano Rico","email":"jmtoledano@ucjc.edu"},
{"name":"José Manuel Valero Esteban","email":"jmvalero@ucjc.edu"},
{"name":"José María Barroso Tristán","email":"jmbarroso@ucjc.edu"},
{"name":"José María Vera Mur","email":"josemaria.vera@ucjc.edu"},
{"name":"José Miguel Alameda Herrador","email":"jmalameda@ucjc.edu"},
{"name":"José Miguel Calvillo Cisneros","email":"jmcalvillo@ucjc.edu"},
{"name":"José Miguel Carrasco Jimeno","email":"jmcarrasco@ucjc.edu"},
{"name":"José Miguel Jiménez París","email":"jmjimenez@ucjc.edu"},
{"name":"José Miguel Santamaría García","email":"jmsantamaria@ucjc.edu"},
{"name":"José Moisés Martín Carretero","email":"jmmartin@ucjc.edu"},
{"name":"José Pedro Marfil","email":"jpmarfil@ucjc.edu"},
{"name":"José Pichel Andrés","email":"p-jpichel@ucjc.edu"},
{"name":"José Silverio Sáez Sesma","email":"sssesma@ucjc.edu"},
{"name":"Juana de las Heras Alonso","email":"jdelasheras@ucjc.edu"},
{"name":"Juana María Gutiérrez Caballero","email":"jmgutierrez@ucjc.edu"},
{"name":"Juana María Santiago García-Ripoll","email":"jsantiago@ucjc.edu"},
{"name":"Juan Andrés Walliser Martínez","email":"jawalliser@ucjc.edu"},
{"name":"Juan Antonio Carrascosa Sanz","email":"jacarrascosa@ucjc.edu"},
{"name":"Juan Antonio Ródenas Ríos","email":"jarodenas@ucjc.edu"},
{"name":"Juan Antonio Valera Calero","email":"javalera@ucjc.edu"},
{"name":"Juan Carlos Arroyo Portero","email":"jcarroyo@ucjc.edu"},
{"name":"Juan Carlos Fernández Rodríguez","email":"jcfernandez@ucjc.edu"},
{"name":"Juan Carlos Ibáñez Rodríguez","email":"jcarlos.ibanez@ucjc.edu"},
{"name":"Juan Carlos Pereira Castañares","email":"jcpereira@ucjc.edu"},
{"name":"Juan Carlos Segovia Martínez","email":"jcsegovia@ucjc.edu"},
{"name":"Juan Carlos Vázquez Pérez","email":"jcvazquez@ucjc.edu"},
{"name":"Juan de Dios Molina Martín","email":"jdmolina@ucjc.edu"},
{"name":"Juan de la Cruz Queipo de Llano Álvarez de Toledo","email":"juan.queipo@sek.es"},
{"name":"Juan Diego Gómez-Escalonilla Torrijos","email":"jdgomez@ucjc.edu"},
{"name":"Juan Díez Nicolás","email":"jdiezn@ucjc.edu"},
{"name":"Juan Emilio Suñé Cano","email":"jsune@ucjc.edu"},
{"name":"Juan Francisco Bellette Tapias","email":"jbellete@ucjc.edu"},
{"name":"Juan Francisco Roy Delgado","email":"jfroy@ucjc.edu"},
{"name":"Juan Heredia Díaz del Riguero","email":"jheredia@ucjc.edu"},
{"name":"Juan Hernández Lougedo","email":"jlougedo@ucjc.edu"},
{"name":"Juan Ignacio Criado Grande","email":"p-jicriado@ucjc.edu"},
{"name":"Juan José López García","email":"jjlopez@ucjc.edu"},
{"name":"Juan José Ramos Álvarez","email":"jjramos@ucjc.edu"},
{"name":"Juan José Salinero Martín","email":"jjsalinero@ucjc.edu"},
{"name":"Juan Luis Botella Ruiz-Castillo","email":"jlbotella@ucjc.edu"},
{"name":"Juan Luis Sierra Domínguez","email":"jlsierra@ucjc.edu"},
{"name":"Juan Manuel Campo Cabal","email":"jmcampo@ucjc.edu"},
{"name":"Juan Manuel Corchado Rodríguez","email":"p-jmcorchado@ucjc.edu"},
{"name":"Juan Pablo Hervás Pérez","email":"jphervas@ucjc.edu"},
{"name":"Juan Padilla Fernández-Vega","email":"jpadilla@ucjc.edu"},
{"name":"Juan Ramos Cejudo","email":"jramos@ucjc.edu"},
{"name":"Juan Redondo Justo","email":"jredondo@ucjc.edu"},
{"name":"Juan Sebastián Lucas Valero","email":"jslucas@ucjc.edu"},
{"name":"Juan Vázquez Rojo","email":"jvazquez@ucjc.edu"},
{"name":"Juan Vicente Bonilla García","email":"jvbonilla@ucjc.edu"},
{"name":"Julián López Yáñez","email":"jlopezy@ucjc.edu"},
{"name":"Julio César Pérez Herrero","email":"jcherrero@ucjc.edu"},
{"name":"Julio Emilio Sandubete Galán","email":"jemilio.sandubete@ucjc.edu"},
{"name":"Julio Emilio Sandubete Galán","email":"jsandubete@ucjc.edu"},
{"name":"Julio Lleonart Crespo","email":"jlleonart@ucjc.edu"},
{"name":"June Ida Burke","email":"jburke@ucjc.edu"},
{"name":"Kamal Antonio Romero Sookoo","email":"karomero@ucjc.edu"},
{"name":"Karl Thomas Derbyshire","email":"kderbyshire@ucjc.edu"},
{"name":"Kyra Balenzano","email":"kmarie.balenzano@ucjc.edu"},
{"name":"Lara Salguero Lucas","email":"lara.salguero@ucjc.edu"},
{"name":"Laura Cuesta Cano","email":"lcuesta@ucjc.edu"},
{"name":"Laura Herrero Pérez","email":"lherrero@ucjc.edu"},
{"name":"Laura Jazmín Bolaños Gómez","email":"lbolanos@ucjc.edu"},
{"name":"Laura Melendo Rodríguez-Carmona","email":"lmelendo@ucjc.edu"},
{"name":"Laura Pesquera Serrano","email":"laura.pesquera@ucjc.edu"},
{"name":"Laura Sánchez Herranz","email":"lsanchez@sek.es"},
{"name":"Laura Sanz Martín","email":"lsanz@ucjc.edu"},
{"name":"Laura Vallejo Slocker","email":"lvallejo@ucjc.edu"},
{"name":"Leonel Victor Groisman Emmi","email":"lvictor.groisman@ucjc.edu"},
{"name":"Leopoldo Alonso Callealta Oña","email":"lcallealta@ucjc.edu"},
{"name":"Leticia León Mateos","email":"lleon@ucjc.edu"},
{"name":"Leticia López Castro","email":"llopezc@ucjc.edu"},
{"name":"Lidia Arroyo Navajas","email":"lidia.arroyo@ucjc.edu"},
{"name":"Lidia Fernández Pereda","email":"lfpereda@ucjc.edu"},
{"name":"Lidia Luque Morales","email":"lluque@ucjc.edu"},
{"name":"Lino González García","email":"lgonzalezg@ucjc.edu"},
{"name":"Lluis Alexandre Casanovas Blanco","email":"lcasanovas@ucjc.edu"},
{"name":"Lorena Aguilar Zapata","email":"laguilar@ucjc.edu"},
{"name":"Lourdes De Serranos Jiménez","email":"lourdes.serranos@ucjc.edu"},
{"name":"Lucía Isabel Fuentes Arroyo","email":"lfuentes@ucjc.edu"},
{"name":"Lucía López Sánchez","email":"llopez@ucjc.edu"},
{"name":"Luciano Joaquín Campos Borensztejn","email":"ljcampos@ucjc.edu"},
{"name":"Luciano Manuel Pérez De la Lama","email":"lmperez@ucjc.edu"},
{"name":"Luisa María Cervantes Duarte","email":"lmcervantes@ucjc.edu"},
{"name":"Luis Antonio Bravo Coromina","email":"lbravo@ucjc.edu"},
{"name":"Luis Calandre Burgueros","email":"lcalandre@ucjc.edu"},
{"name":"Luis Enrique Cabrera Hernández","email":"lecabrera@ucjc.edu"},
{"name":"Luis Enrique Jesús Nazaret Solís Mendoza","email":"lesolis@ucjc.edu"},
{"name":"Luis Fernández Reneo","email":"lfreneo@ucjc.edu"},
{"name":"Luis Fernando Fernández Sánchez","email":"lfsanchez@ucjc.edu"},
{"name":"Luis Jesús González Barato","email":"ljgonzalez@ucjc.edu"},
{"name":"Luis Jiménez Rodríguez","email":"ljimenezr@ucjc.edu"},
{"name":"Luis Marijuan De Santiago","email":"lmarijuan@ucjc.edu"},
{"name":"Luis Martín Carrera De Figueras","email":"lcarrera@ucjc.edu"},
{"name":"Luis Moliner","email":"lmoliner@ucjc.edu"},
{"name":"Luz Florinda Pérez Sánchez","email":"lfperez@ucjc.edu"},
{"name":"Macarena Rodríguez González","email":"mrgonzalez@ucjc.edu"},
{"name":"Maggie Cornejo","email":"mann.cornejo@ucjc.edu"},
{"name":"Maitane Elorriaga Rubio","email":"melorriaga@ucjc.edu"},
{"name":"Manuel Antonio Martínez Ruiz","email":"mamruiz@ucjc.edu"},
{"name":"Manuel Borobio Sanchiz","email":"mborobio@ucjc.edu"},
{"name":"Manuel Carlos García Touriñán","email":"mcgarcia@ucjc.edu"},
{"name":"Manuel Ceballos Biondi","email":"mceballos@ucjc.edu"},
{"name":"Manuel Eugenio López-Medel Bascones","email":"mlmedel@ucjc.edu"},
{"name":"Manuel Felipe Lara Romero","email":"mflara@ucjc.edu"},
{"name":"Manuel Gentil Adarve","email":"mgentil@ucjc.edu"},
{"name":"Manuel José González León","email":"mjgonzalez@ucjc.edu"},
{"name":"Manuel José Iglesias García","email":"mjiglesias@ucjc.edu"},
{"name":"Manuel Juan Silva Maldonado","email":"mjsilva@ucjc.edu"},
{"name":"Manuel Lucas Matheu","email":"mlucasm@ucjc.edu"},
{"name":"Manuel Mondedeu Martínez","email":"mmondedeu@ucjc.edu"},
{"name":"Manuel Moreno Preciado","email":"mmoreno@ucjc.edu"},
{"name":"Manuel Nevado Rey","email":"mnevado@ucjc.edu"},
{"name":"Manuel Nofuentes Caballero","email":"mnofuentes@ucjc.edu"},
{"name":"Manuel Revuelta Zamorano","email":"mrevuelta@ucjc.edu"},
{"name":"Manuel Romero Higes","email":"mromero@ucjc.edu"},
{"name":"Manuel Sillero Quintana","email":"msillero@ucjc.edu"},
{"name":"Mara Fuertes Gutiérrez","email":"mfuertes@ucjc.edu"},
{"name":"Marc Benjami Escolà Pons","email":"mbescola@ucjc.edu"},
{"name":"Marcos Antonio Soriano Rodríguez","email":"msoriano@ucjc.edu"},
{"name":"Marcos Díaz Martín","email":"mdiazm@ucjc.edu"},
{"name":"Marcos José Navarro Santana","email":"mjose.navarros@ucjc.edu"},
{"name":"Marcos Rodríguez López","email":"marcos.rodriguezl@ucjc.edu"},
{"name":"Margarita Alcaide Risoto","email":"malcaide@ucjc.edu"},
{"name":"Margarita Blanco Pérez","email":"mblancop@ucjc.edu"},
{"name":"Margarita Esperanza Núñez Canal","email":"mnunez@ucjc.edu"},
{"name":"Margarita Trejo Poison","email":"mtrejo@ucjc.edu"},
{"name":"Maria Amalia Carvalho Guimaraes","email":"mcarvalho@ucjc.edu"},
{"name":"María Ana Hernández-Sampelayo Matos","email":"msampelayo@ucjc.edu"},
{"name":"María Ángeles Altozano Soler","email":"maaltozano@ucjc.edu"},
{"name":"María Ángeles De la Morena Taboada","email":"mmorena@ucjc.edu"},
{"name":"María Ángeles Fernández González-Regueral","email":"afernandezgr@ucjc.edu"},
{"name":"María Ángeles Fernández López","email":"mafernandez@ucjc.edu"},
{"name":"María Antonia Casanova Rodríguez","email":"acasanova@ucjc.edu"},
{"name":"María Antonia Nerín Rotger","email":"manerin@ucjc.edu"},
{"name":"María Antonieta Elvira Valdés","email":"aelvira@ucjc.edu"},
{"name":"María Aranzazu Carrasco Temiño","email":"acarrasco@ucjc.edu"},
{"name":"María Aránzazu Sánchez Calabuig","email":"masanchez@ucjc.edu"},
{"name":"María Ascensión Escamilla Valera","email":"maescamilla@ucjc.edu"},
{"name":"María Begoña Planells Hernani","email":"mbplanells@ucjc.edu"},
{"name":"María Begoña Sopena Egusquiza","email":"bsopena@ucjc.edu"},
{"name":"María Belén Andueza López","email":"bandueza@ucjc.edu"},
{"name":"María Benito de Pedro","email":"mbenito@ucjc.edu"},
{"name":"María Bravo Rodríguez","email":"maria.brodriguez@ucjc.edu"},
{"name":"María Cabezas García","email":"mcabezas@ucjc.edu"},
{"name":"María Carmen Bogónez Dávila","email":"mcbogonez@ucjc.edu"},
{"name":"María Carmen Capilla Rodríguez","email":"mcarmen.capilla@ucjc.edu"},
{"name":"María Carmen González Álvarez","email":"mcgonzalez@ucjc.edu"},
{"name":"María Criado Crespo","email":"mcriado@ucjc.edu"},
{"name":"María Cristina Cañamero Alvarado","email":"ccanamero@ucjc.edu"},
{"name":"María de Aránzazu Mitjavila Casanovas","email":"mamitjavila@ucjc.edu"},
{"name":"María de la Paloma Herráez García","email":"mla.herraez@ucjc.edu"},
{"name":"María de la Puente Bernardos","email":"mpuente@ucjc.edu"},
{"name":"María de las Mercedes Romero Rodrigo","email":"mmromero@ucjc.edu"},
{"name":"María del Carmen Lozano Estevan","email":"mclozano@ucjc.edu"},
{"name":"María del Carmen Martín Curto","email":"mcmartin@ucjc.edu"},
{"name":"María del Carmen Pellicer Iborra","email":"mariadelcarmen.pellicer@ucjc.edu"},
{"name":"María del Mar Soria Ibáñez","email":"msoria@ucjc.edu"},
{"name":"María de los Ángeles Bueno Villaverde","email":"abueno@ucjc.edu"},
{"name":"María de los Ángeles Domínguez Roldán","email":"madominguezr@ucjc.edu"},
{"name":"María de los Ángeles Pociño Brioa","email":"mapocino@ucjc.edu"},
{"name":"María de los Ángeles Puga Zuccotti","email":"mapuga@ucjc.edu"},
{"name":"María del Pilar Antolínez Merchán","email":"pantolinez@ucjc.edu"},
{"name":"María del Pilar García García","email":"mpgarcia@ucjc.edu"},
{"name":"María del Pilar Jiménez Martínez","email":"mpjimenez@ucjc.edu"},
{"name":"María del Pilar Muñoz Deleito","email":"mpmunoz@ucjc.edu"},
{"name":"María del Pilar Posadas de Julián","email":"mpposadas@ucjc.edu"},
{"name":"María del Rosario Vázquez López","email":"mvazquez@ucjc.edu"},
{"name":"María de Rosario Delso","email":"mrdelso@ucjc.edu"},
{"name":"María Dolores Algora Weber","email":"mdalgora@ucjc.edu"},
{"name":"María Dolores López Salmerón","email":"mdolores.lopezs@ucjc.edu"},
{"name":"María Dolores Ouro Agromartín","email":"mdouro@ucjc.edu"},
{"name":"María Dolores Rueda Montero","email":"drueda@ucjc.edu"},
{"name":"María Domínguez Calleja","email":"mdcalleja@ucjc.edu"},
{"name":"María Ela Rubio Jiménez","email":"mrubio@ucjc.edu"},
{"name":"María Elena Marta Pérez Rodríguez","email":"memperez@ucjc.edu"},
{"name":"María Elena Turrado Domínguez","email":"meturrado@ucjc.edu"},
{"name":"María Emilia Samit Francés","email":"mariaemilia.samit@ucjc.edu"},
{"name":"María Encarnación Castillo Sánchez","email":"mecastillo@ucjc.edu"},
{"name":"María Encarnación Llamas Pérez","email":"mllamas@ucjc.edu"},
{"name":"María Esther Prieto Marín","email":"meprieto@ucjc.edu"},
{"name":"María Esther Valdés Tejera","email":"evaldes@ucjc.edu"},
{"name":"María Fátima Vega Romero","email":"fatima.vega@ucjc.edu"},
{"name":"María Fernanda Del Real García","email":"freal@ucjc.edu"},
{"name":"María Froiz Agudo","email":"mfroiz@ucjc.edu"},
{"name":"María Gabriela Ortega Jarrín","email":"mgortega@ucjc.edu"},
{"name":"María Gómez Lobo Ortega","email":"mglobo@ucjc.edu"},
{"name":"María González Moreno","email":"mgonzalez@ucjc.edu"},
{"name":"María Guadalupe Dorado Escribano","email":"mgdorado@ucjc.edu"},
{"name":"María Ifara Pérez López","email":"iperez@ucjc.edu"},
{"name":"María Inmaculada Álvarez Frutos","email":"mialvarez@ucjc.edu"},
{"name":"María Inmaculada Cortés Calvo","email":"mcortes@ucjc.edu"},
{"name":"María Inmaculada Ruiz Fincias","email":"miruiz@ucjc.edu"},
{"name":"María Isabel García Senent","email":"misabel.garcias@ucjc.edu"},
{"name":"María Isabel Gómez León","email":"migomez@ucjc.edu"},
{"name":"María Isabel Herrera Prieto","email":"iherrera@ucjc.edu"},
{"name":"María Isabel Marañón Garrido","email":"imaranon@ucjc.edu"},
{"name":"María Isabel Ortega Casado","email":"miortega@ucjc.edu"},
{"name":"María Jesús Perea Villena","email":"mjperea@ucjc.edu"},
{"name":"María Jesús Retana Maqueda","email":"mretana@ucjc.edu"},
{"name":"María José Carretero Cenjor","email":"mjcarretero@ucjc.edu"},
{"name":"María José De Dios Pérez","email":"mjdedios@ucjc.edu"},
{"name":"María José Flores Tena","email":"mjflores@ucjc.edu"},
{"name":"María Lamprecht Grandio","email":"maria.lamprecht@ucjc.edu"},
{"name":"María Lourdes Alcalá Ibáñez","email":"marialourdes.alcala@ucjc.edu"},
{"name":"María Luisa Martínez Martí","email":"mmmarti@ucjc.edu"},
{"name":"María Manuela Cobos Navidad","email":"mmcobos@ucjc.edu"},
{"name":"María Martí Marcos","email":"mmarti@ucjc.edu"},
{"name":"María Martín Brualla","email":"mmartin@ucjc.edu"},
{"name":"María Menchen Rubio","email":"mmenchen@ucjc.edu"},
{"name":"María Mercé Berengueras Pont","email":"mariamerce.berengueras@ucjc.edu"},
{"name":"María Mercedes Llop Pomares","email":"mmllop@ucjc.edu"},
{"name":"Mariano Hernán García","email":"mhernan@ucjc.edu"},
{"name":"María Olalla Jiménez Olalde","email":"molalla@ucjc.edu"},
{"name":"María Paz Fernández García","email":"mpfernandez@ucjc.edu"},
{"name":"María Paz Franco Módenes","email":"pfranco@ucjc.edu"},
{"name":"María Paz Muguerza Goya","email":"pmuguerza@ucjc.edu"},
{"name":"María Perales Santaella","email":"mperales@ucjc.edu"},
{"name":"María Petronela Popiuc","email":"mpopiuc@ucjc.edu"},
{"name":"María Piedad Lumera Galindo","email":"mpiedad.lumera@ucjc.edu"},
{"name":"María Pilar Baquero Navarro","email":"mpbaquero@ucjc.edu"},
{"name":"Maria Pilar De Terán Temprano","email":"mpdeteran@ucjc.edu"},
{"name":"María Pilar González Lozano","email":"mlozano@ucjc.edu"},
{"name":"María Pilar González Panero","email":"mpgonzalez@ucjc.edu"},
{"name":"María Pilar Rodrigo Moriche","email":"prodrigo@ucjc.edu"},
{"name":"María Poveda Fernández Martín","email":"pfernandez@ucjc.edu"},
{"name":"María Provencio Ortega","email":"mprovencio@ucjc.edu"},
{"name":"María Raquel Armas Zavaleta","email":"rarmas@ucjc.edu"},
{"name":"María Raquel Picornell Buendía","email":"rpicornell@ucjc.edu"},
{"name":"María Reyes Molero Aparicio","email":"mreyes.molero@ucjc.edu"},
{"name":"María Ródenas Ríos","email":"maria.rodenas@ucjc.edu"},
{"name":"María Rodríguez Suárez","email":"maria.rodriguez18@ucjc.edu"},
{"name":"María Rosa Jurado Barba","email":"mrjurado@ucjc.edu"},
{"name":"María Rosa Marcelina Alonso Melero","email":"mralonso@ucjc.edu"},
{"name":"María Rosario López Giménez","email":"mrolopez@ucjc.edu"},
{"name":"María Ruiz Ortiz","email":"mruizo@ucjc.edu"},
{"name":"María Sánchez Prieto","email":"msanchez@ucjc.edu"},
{"name":"María Soledad Cirujano Garzo","email":"scirujano@ucjc.edu"},
{"name":"María Teresa Alonso-Miñón Agut","email":"mariateresa.alonsominon@sek.es"},
{"name":"María Teresa García Pastor","email":"tgarcia@ucjc.edu"},
{"name":"María Teresa Lavín Dapena","email":"tlavin@ucjc.edu"},
{"name":"María Vera Mencías","email":"mvera@ucjc.edu"},
{"name":"María Victoria Ramírez Crespo","email":"mvramirez@ucjc.edu"},
{"name":"Marina Gómez de Quero Córdoba","email":"mgomez@ucjc.edu"},
{"name":"Marina Rosell Jiménez","email":"mrosell@ucjc.edu"},
{"name":"Marina Wobbeking Sánchez","email":"mwobbeking@ucjc.edu"},
{"name":"Mario Arias Oliva","email":"marias@ucjc.edu"},
{"name":"Mario Caballero Corella","email":"mcaballero@ucjc.edu"},
{"name":"Mario Pérez Pardo","email":"mperezp@ucjc.edu"},
{"name":"Mark Stuart Evamy","email":"mstuart.evamy@ucjc.edu"},
{"name":"Marta Beatriz López Sánchez","email":"mblopez@ucjc.edu"},
{"name":"Marta Carrasco Ferrer","email":"mcarrasco@ucjc.edu"},
{"name":"Marta Gómez Martín","email":"mgomezm@ucjc.edu"},
{"name":"Marta Gual Oliva","email":"mgual@ucjc.edu"},
{"name":"Marta Hurtado Martín","email":"mhurtado@ucjc.edu"},
{"name":"Marta Larragueta Arribas","email":"mlarragueta@ucjc.edu"},
{"name":"Marta María Redondo Delgado","email":"mredondo@ucjc.edu"},
{"name":"Marta Montilla Sancho","email":"marta.montilla@ucjc.edu"},
{"name":"Marta Sánchez Ordóñez","email":"msanchezo@ucjc.edu"},
{"name":"Marta Serrano Pérez","email":"mserrano@ucjc.edu"},
{"name":"Marta Toral Guinea","email":"mtoral@ucjc.edu"},
{"name":"Martín Anselmo Rocha Espindola","email":"mrocha@ucjc.edu"},
{"name":"Mary Fiona McFall","email":"mmcfall@ucjc.edu"},
{"name":"Mateo Pérez Wiesner","email":"mpwiesner@ucjc.edu"},
{"name":"Maura Jiménez Herranz","email":"mjherranz@ucjc.edu"},
{"name":"Maximiliano Facundo Aguilar Masuelli","email":"maguilar@ucjc.edu"},
{"name":"Max Walter Joseph Römer Pieretti","email":"mwalter@ucjc.edu"},
{"name":"Mayra Martínez Avidad","email":"mmartinez@ucjc.edu"},
{"name":"Mbuyi Kabunda","email":"mkabunda@ucjc.edu"},
{"name":"Michelle Madeline Cámara Mora","email":"mmcamara@ucjc.edu"},
{"name":"Miguel Ángel Díaz Camacho","email":"macamacho@ucjc.edu"},
{"name":"Miguel Ángel Pérez Nieto","email":"mperez@ucjc.edu"},
{"name":"Miguel Ángel Rejas del Hoyo","email":"mrejas@ucjc.edu"},
{"name":"Miguel Antonio Ortego Ruiz","email":"mortego@ucjc.edu"},
{"name":"Miguel Aranzana Juarros","email":"maranzana@ucjc.edu"},
{"name":"Miguel Arjona Torres","email":"marjona@ucjc.edu"},
{"name":"Miguel Benedicto Solsona","email":"mbenedicto@ucjc.edu"},
{"name":"Miguel Cristóbal García","email":"mcristobal@ucjc.edu"},
{"name":"Miguel Francisco Santos Nevado","email":"mfsantos@ucjc.edu"},
{"name":"Miguel Javier Martínez de Lizarrondo Apesteguía","email":"mmlizarrondo@ucjc.edu"},
{"name":"Miguel Reynés Ramón","email":"mreynes@ucjc.edu"},
{"name":"Miguel Santesmases Navarro de Palencia","email":"msantesmases@ucjc.edu"},
{"name":"Miriam Biel Maeso","email":"miriam.biel@ucjc.edu"},
{"name":"Miriam De los Santos López","email":"mdelossantos@ucjc.edu"},
{"name":"Miriam Salvador García","email":"msalvador@ucjc.edu"},
{"name":"Mónica Jiménez Camacho","email":"mjimenez@ucjc.edu"},
{"name":"Mónica Méndez De la Calle","email":"mmendez@ucjc.edu"},
{"name":"Mónica Prieto Peris","email":"monica.prieto@sek.es"},
{"name":"Mónica San Juan Fernández","email":"msanjuan@ucjc.edu"},
{"name":"Montserrat Díaz Rosell","email":"mdiazr@ucjc.edu"},
{"name":"Montserrat Magro Gutiérrez","email":"mmagro@ucjc.edu"},
{"name":"Montserrat Ruiz López","email":"mrlopez@ucjc.edu"},
{"name":"Moriah Maunu","email":"mflorence.maunu@ucjc.edu"},
{"name":"Nadia Hamade Almeida","email":"nhamade@ucjc.edu"},
{"name":"Nagore Romero Torres","email":"nagore.romero@ucjc.edu"},
{"name":"Natalia Lara Nieto-Márquez","email":"natalia.lara@ucjc.edu"},
{"name":"Natalia María Ochoa Ruiz","email":"nmochoa@ucjc.edu"},
{"name":"Natalia Mondedeu Sanz","email":"nmondedeu@ucjc.edu"},
{"name":"Natalia Rubio Arribas","email":"nrubio@ucjc.edu"},
{"name":"Nathalia Foditsch","email":"p-nfoditsch@ucjc.edu"},
{"name":"Navid Behzadi Koochani","email":"nbehzadi@ucjc.edu"},
{"name":"Nerea Cuenca Orellana","email":"ncuenca@ucjc.edu"},
{"name":"Nicholas Jay Ludwig","email":"nludwig@ucjc.edu"},
{"name":"Noelia Carbonell Bernal","email":"ncarbonell@ucjc.edu"},
{"name":"Noelia Torres Garzarán","email":"ntorre@ucjc.edu"},
{"name":"Noemí Mayoral Gonzalo","email":"nmayoral@ucjc.edu"},
{"name":"Noemi Parra Abaúnza","email":"noemi.abaunza@ucjc.edu"},
{"name":"Nuño Aguirre de Cárcer Girón","email":"naguirre@ucjc.edu"},
{"name":"Nuria Álvarez González","email":"nalvarez@ucjc.edu"},
{"name":"Nuria Cantero Rodríguez","email":"ncantero@ucjc.edu"},
{"name":"Olga Beatriz Moreno Almendros","email":"obeatriz.moreno@ucjc.edu"},
{"name":"Olivia Victoria Recondo Pérez","email":"ovrecondo@ucjc.edu"},
{"name":"Olvido Elena Andújar Molina","email":"oeandujar@ucjc.edu"},
{"name":"Oriana María Ramírez Rubio","email":"oramirez@ucjc.edu"},
{"name":"Orlando D´Adamo","email":"odadamo@ucjc.edu"},
{"name":"Óscar Francisco Díaz Santana","email":"ofdiaz@ucjc.edu"},
{"name":"Óscar René Montes Pineda","email":"omontes@ucjc.edu"},
{"name":"Óscar Teston Udaondo","email":"oteston@ucjc.edu"},
{"name":"Pablo Ángel Félix Del Cueto","email":"pfelix@ucjc.edu"},
{"name":"Pablo Escudero Abenza","email":"pablo.escuderoa@ucjc.edu"},
{"name":"Pablo Fernández Alonso","email":"pablo.falonso@ucjc.edu"},
{"name":"Pablo Gómez Sesé","email":"pgomez@ucjc.edu"},
{"name":"Pablo Martín Diez","email":"pmdiez@ucjc.edu"},
{"name":"Pablo Navazo Ostúa","email":"pnavazo@ucjc.edu"},
{"name":"Paloma Robles Llana","email":"probles@ucjc.edu"},
{"name":"Patricia Blanco Hermo","email":"pblanco@ucjc.edu"},
{"name":"Paula Guisado Molina","email":"pguisado@ucjc.edu"},
{"name":"Paula Requeijo Rey","email":"prequeijo@ucjc.edu"},
{"name":"Paula Zamorano Caballero","email":"pzamorano@ucjc.edu"},
{"name":"Pedro Aurelio Viñuela Villa","email":"avinuela@ucjc.edu"},
{"name":"Pedro Flores Jiménez","email":"pflores@ucjc.edu"},
{"name":"Pedro Javier Vega Ballesteros","email":"pjvega@ucjc.edu"},
{"name":"Pedro Párraga Marchal","email":"pparraga@sek.es"},
{"name":"Peter Raphael Greiff","email":"pgreiff@ucjc.edu"},
{"name":"Pilar Ester Mariñoso","email":"pester@ucjc.edu"},
{"name":"Pilar Marín Gómez","email":"pmgomez@ucjc.edu"},
{"name":"Pilar Vázquez Hernández","email":"pvazquez@ucjc.edu"},
{"name":"Presentación Ángeles Caballero García","email":"pcaballero@ucjc.edu"},
{"name":"Pruebas Validación Dominio SEK","email":"bbsek@sek.es"},
{"name":"Rafael Añez Garrido","email":"ranez@ucjc.edu"},
{"name":"Rafael Calduch Cervera","email":"rccervera@ucjc.edu"},
{"name":"Rafael Calduch Torres","email":"rctorres@ucjc.edu"},
{"name":"Rafael Conde Melguizo","email":"rconde@ucjc.edu"},
{"name":"Rafael Delgado Vázquez","email":"rdelgadov@ucjc.edu"},
{"name":"Rafael Hernández López","email":"rahernandez@ucjc.edu"},
{"name":"Rafael Herrero García","email":"rherrero@ucjc.edu"},
{"name":"Rafael León Sanz","email":"rleon@ucjc.edu"},
{"name":"Rafael Magro Andrade","email":"rmagro@ucjc.edu"},
{"name":"Rafael Moreno Izquierdo","email":"rmizquierdo@ucjc.edu"},
{"name":"Rafael Villa Martínez","email":"rvilla@ucjc.edu"},
{"name":"Ramiro Mínguez Rueda","email":"rminguez@ucjc.edu"},
{"name":"Ramón Bonell Colmenero","email":"rbonell@ucjc.edu"},
{"name":"Ramón García García","email":"ragarcia@ucjc.edu"},
{"name":"Ramón Vázquez Negro","email":"rvazquez@ucjc.edu"},
{"name":"Raquel Bravo Blázquez","email":"rbravob@ucjc.edu"},
{"name":"Raquel Delgado Delgado","email":"rdelgado@ucjc.edu"},
{"name":"Raquel Moreno Sánchez","email":"ramoreno@ucjc.edu"},
{"name":"Raquel Osorno Gil","email":"rosorno@ucjc.edu"},
{"name":"Rebeca Fraile Cubero","email":"rfraile@ucjc.edu"},
{"name":"Regina Espinosa López","email":"respinosa@ucjc.edu"},
{"name":"Renata Valle Lapeña","email":"rvalle@ucjc.edu"},
{"name":"Ricardo Amado Castillo","email":"p-ramado@ucjc.edu"},
{"name":"Ricardo Antonio Cortines Barcena","email":"rcortines@ucjc.edu"},
{"name":"Ricardo Blázquez Arroyo","email":"rblazquez@ucjc.edu"},
{"name":"Ricardo Carreras Lario","email":"rcarreras@ucjc.edu"},
{"name":"Ricardo García Vegas","email":"p-rgarcia@ucjc.edu"},
{"name":"Ricardo Javier Presol Castillo","email":"jpresol@sek.es"},
{"name":"Ricardo José Rejas Muslera","email":"rrejas@ucjc.edu"},
{"name":"Ricardo Rodríguez Barrientos","email":"rbarrientos@ucjc.edu"},
{"name":"Ricardo Sánchez Orzáez","email":"rsanchez@ucjc.edu"},
{"name":"Richard John Armstrong","email":"rick.armstrong@ucjc.edu"},
{"name":"Roberto Fernández Fernández","email":"rfernandez@ucjc.edu"},
{"name":"Roberto Moreno López","email":"rmoreno@ucjc.edu"},
{"name":"Roberto Muñoz Bolaños","email":"rmunoz@ucjc.edu"},
{"name":"Roberto Murias Lozano","email":"rmurias@ucjc.edu"},
{"name":"Rocío López González","email":"rlopezg@ucjc.edu"},
{"name":"Rodrigo Ferrer García","email":"rferrer@ucjc.edu"},
{"name":"Rogelio Ballestero López","email":"rogelio.ballestero@ucjc.edu"},
{"name":"Román Darío Moreno Fernández","email":"rdmoreno@ucjc.edu"},
{"name":"Rosa María Martín Galván","email":"rmmartin@ucjc.edu"},
{"name":"Rosa María Ventas Sastre","email":"rmventas@ucjc.edu"},
{"name":"Rosa Pérez Arozamena","email":"rpereza@ucjc.edu"},
{"name":"Roxana Valverde Ponce","email":"rvalverde@ucjc.edu"},
{"name":"Rubén Trigueros Ramos","email":"rtrigueros@ucjc.edu"},
{"name":"Ruth Galeano Godoy","email":"rgaleano@ucjc.edu"},
{"name":"Ruth Pilar Castillo Gualda","email":"rcastillo@ucjc.edu"},
{"name":"Salomé Berrocal Gonzalo","email":"sberrocal@ucjc.edu"},
{"name":"Samuel Fernández-Salinero San Martín","email":"sfernandezs@ucjc.edu"},
{"name":"Sandra Balaguer Solé","email":"sbalaguer@ucjc.edu"},
{"name":"Sandra García Sinausía","email":"sgarcia@ucjc.edu"},
{"name":"Sandra González Miguel","email":"sgonzalez@ucjc.edu"},
{"name":"Sandra Rudy Cobo","email":"srudy@ucjc.edu"},
{"name":"Sandra Ruiz Ambit","email":"sruiza@ucjc.edu"},
{"name":"Sandra Sotomayor Núñez","email":"ssotomayor@ucjc.edu"},
{"name":"Santiago Espinosa Blanco","email":"santiago.espinosab@ucjc.edu"},
{"name":"Santiago García de Leaniz Caprile","email":"sgarciadeleaniz@ucjc.edu"},
{"name":"Santiago Sánchez Regadera","email":"ssregadera@ucjc.edu"},
{"name":"Sara Cabañas Area","email":"scabanas@ucjc.edu"},
{"name":"Sara Calderón Esteban","email":"scalderon@ucjc.edu"},
{"name":"Sara Ruiz Sanjuán","email":"srsanjuan@ucjc.edu"},
{"name":"Sara Sánchez Ruiz","email":"ssanchez@ucjc.edu"},
{"name":"Sari Marjaana Arponen","email":"smarponen@ucjc.edu"},
{"name":"Sebastián Francisco Truyols Domínguez","email":"struyols@ucjc.edu"},
{"name":"Sergio Martínez Pacheco","email":"smartinezp@ucjc.edu"},
{"name":"Sergio Toba Domínguez","email":"stoba@ucjc.edu"},
{"name":"Sergio Tobías Sidera","email":"sergio.tobias@ucjc.edu"},
{"name":"Sheila Lucero Sánchez López","email":"ssanchezl@ucjc.edu"},
{"name":"Silvia Aranda García","email":"silvia.aranda@ucjc.edu"},
{"name":"Silvia Blas Obispo","email":"sblas@ucjc.edu"},
{"name":"Silvia Castellanos Cano","email":"scastellanos@ucjc.edu"},
{"name":"Silvia De la Calle Guerra","email":"silvia.calleg@ucjc.edu"},
{"name":"Silvia Herrero Roldán","email":"silvia.herreror@ucjc.edu"},
{"name":"Silvia Simón Eguizábal","email":"ssimon@ucjc.edu"},
{"name":"Sofía Olivia Calvo Moreno","email":"socalvo@ucjc.edu"},
{"name":"Sofía Unda Benkhadra","email":"sunda@ucjc.edu"},
{"name":"Sol Iturbe González","email":"sol.iturbe@ucjc.edu"},
{"name":"Sonia Alda Mejías","email":"salda@ucjc.edu"},
{"name":"Sonia Betancort Santos","email":"sbetancort@ucjc.edu"},
{"name":"Sonia Laura Carcelén García","email":"slcarcelen@ucjc.edu"},
{"name":"Sonia Sánchez Martínez","email":"smartinez@ucjc.edu"},
{"name":"Soraya Calvo González","email":"scgonzalez@ucjc.edu"},
{"name":"Soraya Serrano Matamoros","email":"soraya.serrano@ucjc.edu"},
{"name":"Stefano Visintin","email":"svisintin@ucjc.edu"},
{"name":"Susana Beatriz Fernández","email":"sbfernandez@ucjc.edu"},
{"name":"Susana Inés Pérez Alonso","email":"sperez@ucjc.edu"},
{"name":"Susana Laguna Hermida","email":"slaguna@ucjc.edu"},
{"name":"Susana María Ferrada Castro","email":"smaria.ferrada@ucjc.edu"},
{"name":"Susana Moreno Pachón","email":"smoreno@ucjc.edu"},
{"name":"Susana San Cristóbal Reales","email":"ssancristobal@ucjc.edu"},
{"name":"Teodoro Pascual Nicolás","email":"tpascual@ucjc.edu"},
{"name":"Teresa María Ramos Martín","email":"tmaria.ramosm@ucjc.edu"},
{"name":"Teresa Sanz Cuesta","email":"tsanz@ucjc.edu"},
{"name":"Teresa Viejo","email":"tviejo@ucjc.edu"},
{"name":"Teresita de Lourdes Bernal Romero","email":"tbernal@ucjc.edu"},
{"name":"Tesa Pribitkin","email":"yteresa.pribitkin@ucjc.edu"},
{"name":"Timothy Appleton","email":"tappleton@ucjc.edu"},
{"name":"Tomás Fernández Rodríguez","email":"tfernandez@ucjc.edu"},
{"name":"Tomás García Martín","email":"tgmartin@ucjc.edu"},
{"name":"Tomás Sebastián Viana","email":"tsebastian@ucjc.edu"},
{"name":"Valentín Martín Manzanero","email":"valentin.martin@ucjc.edu"},
{"name":"Vanesa Gallego Mengod","email":"vanesa.gallego@ucjc.edu"},
{"name":"Verónica Giráldez Costas","email":"vgiraldez@ucjc.edu"},
{"name":"Verónica Rose Steffen","email":"vsteffen@ucjc.edu"},
{"name":"Verónica Valverde González","email":"vvalverde@ucjc.edu"},
{"name":"Vicente Garrido Rebolledo","email":"vgarrido@ucjc.edu"},
{"name":"Vicente Luque Centeno","email":"vluque@ucjc.edu"},
{"name":"Víctor Gómez Sánchez","email":"vgomez@ucjc.edu"},
{"name":"Victor Herreruela Ruiz","email":"vherreruela@ucjc.edu"},
{"name":"Victoria Eugenia Garnacho Garnacho","email":"vegarnacho@ucjc.edu"},
{"name":"Victoria Mazoteras Pardo","email":"vmazoteras@ucjc.edu"},
{"name":"Víctor Jiménez Díaz-Benito","email":"vjdiaz-benito@ucjc.edu"},
{"name":"Víctor José Zubizarreta Ballesteros","email":"v.zubizarreta@ucjc.edu"},
{"name":"Víctor Paredes Hernández","email":"vparedes@ucjc.edu"},
{"name":"Víctor Tomás Soria García","email":"vtsoria@ucjc.edu"},
{"name":"Violeta Miguel Pérez","email":"vmiguel@ucjc.edu"},
{"name":"Virginia Beaudoux","email":"vigarcia@ucjc.edu"},
{"name":"Xavier Bocquier Leplain","email":"xbocquier@ucjc.edu"},
{"name":"Yolanda Cuevas Labrador","email":"ycuevas@ucjc.edu"},
{"name":"Yolanda Isabel Requena Silla","email":"yolanda.requena@sek.es"},
{"name":"Zaida Moreno Villegas","email":"zmoreno@ucjc.edu"},
{"name":"Zorann Petrovici","email":"zpetrovici@ucjc.edu"},
]

describe('Test .env values', () => {
  test('Check baseEndpointURL (Test API)', () => {
    expect(baseEndpointURL).toBe(baseEndpointURLValue);
  })
  test('Check faculty value', () => {
    expect(scormFacultyValues).toContain(scormFaculty);
  })
  test('Check degree value', () => {
    expect(scormDegreeValues).toContain(scormDegree);
  })
  test('Check teachers name', () => {
      const authors = scormAuthors.split('|');
      const scormAuthorNameValues = scormAuthorValues.map(elem => elem.name);
      authors.forEach(author => {
          expect(scormAuthorNameValues).toContain(author);
      })
  })
  test('Check teachers email', () => {
      const emails = scormAuthorEmails.split('|');
      const scormAuthorEmailValues = scormAuthorValues.map(elem => elem.email);
      emails.forEach(email => {
          expect(scormAuthorEmailValues).toContain(email);
      })
  })
  test('Check SCORM name', () => {
     expect(scormName).toBe(configuration[0].children[0].props.title);
  })
  test('Check SCORM pages', () => {
     expect(parseInt(scormPages)).toBe(configuration.length);
  })
})

// describe('Evaluation', () => {
//   test('Check baseEndpointURL (Test API)', () => {
//     const values = {
        
//     }
//     const {container} = render(<Evaluation scorm={values} />);

//     const button = getByTestId(container, 'evaluation__button');
//     fireEvent.click(button);
//     expect(Evaluation.state.currentPosition).toBe(1);
//   })
// })